platform :ios, '9.0'
use_frameworks!

xcodeproj 'mapSearch.xcodeproj'
target 'mapSearch' do
pod 'Masonry', '~> 1.1.0'
pod 'AFNetworking', '~> 3.1.0'

pod 'SwpNetworking', '~> 1.0.4'
pod 'MJExtension', '~> 3.0.13'

pod 'MBProgressHUD', '~> 1.1.0'

end
